### ISSUE TITLE
Unrecognised protocol?

### ISSUE THREAD

**Issue by gidoBOSSftw5731** [Diablo-D3/DiabloMiner#86]
```bash
$ ./DiabloMiner-Linux.sh -l stratum+tcp://gido5731.worker1:foo@us.ss.btc.com:443
Exception in thread "main" java.net.MalformedURLException: unknown protocol: stratum+tcp
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at com.diablominer.DiabloMiner.DiabloMiner.execute(DiabloMiner.java:193)
	at com.diablominer.DiabloMiner.DiabloMiner.main(DiabloMiner.java:90)
``` 
thats the protocol the website says to use, confused on why it doesn't work

**Comment by allquixotic** [comment]
Per https://github.com/Diablo-D3/DiabloMiner/issues/84#issuecomment-266826539 

 > DiabloMiner is no longer under development, and does not speak the new miner protocol.

Use cgminer instead.

**Comment by Diablo-D3** [comment]
@allquixotic beat me to it.

Go use cgminer instead.
